name: Generate Auto Documentation
description: "Updates an OpenAPI spec file based on changes to a single API file."
inputs:
  runllm_server_address:
    description: "The full host:port address to the RunLLM instance to use."
    required: false
    default: "api.runllm.com"
  runllm_api_key:
    description: "The API key to use for the RunLLM instance."
    required: true
  github_token:
    description: "The GitHub token to use for the GitHub repository."
    required: true
  input_api_file:
    description: "The file path for the input API file. It is expected to be a Python file."
    required: true
  output_spec_file:
    description: "The file path for the output OpenAPI spec file. It is expected to be a YML file."
    required: true
  base_branch:
    description: 'The base branch for the pull request'
    required: true
    default: 'main'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch main branch
      run: git fetch origin main:main
      shell: bash

    - name: Compute diff against main
      run: git diff ${{ inputs.base_branch }}...HEAD > diff.txt
      shell: bash

    # TODO: use a script instead of a bash command.
    #    - name: Check that the input_api_file was involved in the diff
    #      run: |
    #          if ! grep -q ${{ inputs.input_api_file }} diff.txt; then
    #              echo "Error: The input API file was not involved in the diff. Exiting."
    #              exit 1
    #          fi
    #      shell: bash

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Set GH Action URL
      run: echo "GH_ACTION_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
      shell: bash

    - name: Update OpenAPI Spec
      env:
        GITHUB_REPO_NAME: ${{ github.repository}}
      run: |
        python scripts/generate_docs.py \
        --server-address ${{ inputs.runllm_server_address }} \
        --api-key ${{ inputs.runllm_api_key }} \
        --input-api-file ${{ inputs.input_api_file }} \
        --output-openapi-file ${{ inputs.output_spec_file }} \
        --mode openapi \
        --diffs diff.txt \
      shell: bash

    - id: get-pr-body
      run: |
        body=$(cat pr-body.txt)
        echo "pr_body<<EOF" >> $GITHUB_OUTPUT
        echo "$body"
        echo "EOF"
#        body="${body//'%'/'%25'}"
#        body="${body//$'\n'/'%0A'}"
#        body="${body//$'\r'/'%0D'}"
#        echo "pr_body=${body}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Remove temporary files
      run: rm -rf diff.txt pr-body.txt
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.github_token }}
        commit-message: Update documentation
        title: "Update OpenAPI Spec"
        branch: autogenerated-docs-${{ github.run_id }}
        body: ${{ steps.get-pr-body.outputs.pr_body }}
        base: ${{ inputs.base_branch }}

    # TODO: finish the autodoc workflow